# Workflow used to package the application using PyInstaller
name: "BuildBrowserApp"

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  schedule:
  - cron: '43 6 * * 5'

jobs:
  environment:
    name: Initialize the build container
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Ubuntu build container
      shell: bash
      run: |
        "echo \"Configuring build container by downloading required packages (apt)\"
        sudo apt update
        sudo apt install -y python3 python3-pip python3.10-venv
        sudo apt install qtcreator qtbase5-dev qt5-qmake pyqt5-dev-tools qttools5-dev-tools

  python-venv:
    name: Initialize the Python virtual environment & Dependencies
    needs: environment
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: true

      steps:
      - name: Define Python virtual environment
        shell: bash
        run: |
          echo "Define Python virtual environment"
          python3 -m venv .venv
          chmod u+x .venv/bin/activate
          .venv/bin/activate

      - name: Manage Python dependencies
        shell: bash
        run: |
          echo "Download required Python dependencies (pip)"
          python3 -m pip install --upgrade pip
          python3 -m pip install PyQtWebEngine
          python3 -m pip install sip
          python3 -m pip install PyQt5 --config-settings --confirm-license= --verbose
          python3 -m pip install pyinstaller

  build:
    name: Build the Browser Application
    needs: python-venv
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: true

    steps:
    - name: Build application
      shell: bash
      run: |
        echo "Package the application with pyinstaller"
        pyinstaller --log-level=DEBUG --clean browser.spec
